json.id recipe.id
json.title recipe.title
json.ingredients recipe.ingredients_list
json.directions recipe.directions_list
json.image_url recipe.image_url
json.prep_time recipe.friendly_prep_time
json.created_at recipe.friendly_created_at
json.updated_at recipe.updated_at
json.chef_id recipe.chef_id
json.chef recipe.chef